### PR TITLE
add headers for jekyll

### PR DESCRIPTION
**Pull request by eggshell**
We'll need some headers to tell jekyll how to render our lore on the
bonnyci website.

Depends-On: 
* BonnyCI/bonnyci.github.com#2 
* #59 

Signed-off-by: Cullen Taylor <CullenTaylor@outlook.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/lore/58/1486502723.51/lore : FAILURE in 23s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/lore/58/1486502787.77/lore : FAILURE in 24s

**Comment by eggshell** [comment]
So, jekyll needs a little bit of YAML at the beginning of a markdown file to render it correctly. This is going to pose a conundrum for how me lint these markdown files.

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/lore/58/1486507760.55/lore : FAILURE in 24s

**Comment by eggshell** [comment]
taken care of in BonnyCI/bonnyci#3

**Pull request closed without merging**
